### ISSUE TITLE
THIS IS NOT A PLACE FOR JOKE, PLEASE KEEP ACADEMIC RIGOR!

### ISSUE THREAD

**Issue by weathon** [Alan-Liang/zhongwen-please#1] opened 2019-08-24 20:44 UTC
# THIS IS NOT A PLACE FOR JOKE, PLEASE KEEP ACADEMIC RIGOR!
### THIS IS NOT A PLACE FOR JOKE, PLEASE KEEP ACADEMIC RIGOR!

**Comment by cflw** [comment] 2019-08-25 06:48
蛤？GitHub是用来搞学术的？

https://github.com/komeiji-satori/Dress 了解一下

**Comment by AkiraFukuda** [comment] 2019-08-25 12:45
> 蛤？GitHub是用来搞学术的？
> 
> https://github.com/komeiji-satori/Dress 了解一下

创建这些娱乐向的repo是每个人的自由，但这些repo对作为一个开源社区的GitHub而言不是什么好事。没有人希望这里变成下一个知乎、b站或者Quora。
It's one's freedom to create repos like that, but there's nothing good for GitHub as an open-source platform. Nobody want GitHub to become the next Quora/bilibili/Zhihu.

**Comment by AkiraFukuda** [comment] 2019-08-25 13:00
THIS IS NOT A JOKE. The problem is that if we should give an English translation to help only-English speakers read Chinese readmes, shouldn't we give a Chinese translation to help only-Chinese speakers read English readmes?

**Comment by Alan-Liang** [comment] 2019-08-25 14:11
@AkiraFukuda Well this is actually a joke... Just without enough time to be done.

Sorry for the latency of reply. As far as I am concerned, GitHub is not just an open-source platform. See these:

- https://github.com/kelseyhightower/nocode
- https://github.com/hamukazu/lets-get-arrested
- https://github.com/samshadwell/TrumpScript
- https://github.com/996icu/996.ICU
- https://github.com/fuckcqcs/fuckcqcs
- https://github.com/upend/IF_MS_BUYS_GITHUB_IMMA_OUT
- ......

Anyway, I consider this repo is inappropriate for sure, so closing this issue & removing this repo from GitHub. Thank you all for reminding me.

**Closed by Alan-Liang** 2019-08-25 14:11 UTC
Labels: good first issue
